import React, { useState, useEffect, useRef } from 'react';
import Menu from './Menu';
import { Link } from "react-router-dom";
// import { Link } from 'react-router-dom';
import "./Orders.css";

const StockBot = () => {
  const [messages, setMessages] = useState([
    { sender: 'bot', text: "Hello! I'm your stock trading assistant. Ask me anything about stocks, trading strategies, or market trends! 📈" }
  ]);
  const [query, setQuery] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const dummyResponses = {
    'hello': '👋 Hello there! How can I assist with your trading questions today?',
    'hi': '👋 Hi! Ready to talk stocks?',
    'what is your name': 'My name is Nova    (❁´◡`❁)    and I am specially designed to resolve your problem',
    'stock': 'A stock represents ownership in a company.',
    'portfolio': 'A portfolio is a collection of investments.',
    'bull market': 'A bull market means prices are rising.',
    'bear market': 'A bear market means prices are falling.',
    'dividend': 'A dividend is a payout to shareholders.',
    'market cap': 'Market capitalization is share price times number of shares.',
    'ipo': 'IPO stands for Initial Public Offering.',
    'mutual fund': 'A mutual fund pools investor money into a portfolio.',
    'thanks': 'You’re welcome! 😊',
    'help': 'Ask me about stocks, strategies, or trends!',
    'stock': 'A stock represents ownership in a company. When you buy a stock, you become a shareholder of that company.',
    'equity': 'Equity refers to ownership in assets after all debts associated with those assets are paid off. In trading, it often refers to stock ownership.',
    'portfolio': 'A portfolio is a collection of investments held by an individual or institution. Diversification across asset classes can reduce risk.',
    'bull market': 'A bull market is when stock prices are rising or are expected to rise. It\'s characterized by optimism and investor confidence.',
    'bear market': 'A bear market is when stock prices are falling or are expected to fall. It\'s typically a 20% or more decline from recent highs.',
    'dividend': 'A dividend is a payment made by a corporation to its shareholders, usually as a distribution of profits.',
    'market cap': 'Market capitalization is the total market value of a company\'s outstanding shares. It\'s calculated as share price times number of shares.',
    'blue chip': 'Blue chip stocks are shares of large, well-established companies with a history of financial stability and consistent performance.',
    'ipo': 'An Initial Public Offering (IPO) is when a private company offers shares to the public for the first time.',
    'technical analysis': 'Technical analysis involves evaluating securities by analyzing statistics generated by market activity, such as past prices and volume.',
    'fundamental analysis': 'Fundamental analysis examines financial statements, management, competitive advantages, and market conditions to evaluate a security\'s value.',
    'etf': 'An Exchange-Traded Fund (ETF) is a type of security that tracks an index, sector, commodity, or other assets but trades like a stock on an exchange.',
    'volatility': 'Volatility measures how much the price of a security fluctuates. High volatility often means higher risk but also potential for higher returns.',
    'short selling': 'Short selling is when an investor borrows shares and sells them, hoping to buy them back later at a lower price to return to the lender.',
    'market order': 'A market order is an order to buy or sell a security immediately at the best available current price.',
    'limit order': 'A limit order is an order to buy or sell a security at a specific price or better.',
    'stop loss': 'A stop-loss order is designed to limit an investor\'s loss on a position by automatically selling when the price reaches a specified level.',
    'crypto': 'Cryptocurrencies are digital assets that use cryptography for security. They operate on decentralized networks based on blockchain technology.',
    'roi': 'Return on Investment (ROI) measures the gain or loss generated on an investment relative to the amount of money invested.',
    'thanks': 'You\'re welcome! 😊 Happy trading!',
    'thank you': 'Glad I could help! 💼 Let me know if you have more questions.',
    'help': 'I can explain stock market terms, discuss trading strategies, analyze market trends, and provide educational resources. Try asking: "What is a bear market?" or "How do I diversify my portfolio?"',
    


  "what is equity": "Equity represents ownership in a company. When you buy shares, you own a part of that company.",
  "what is demat account": "A Demat account stores your shares electronically instead of paper format.",
  "how to buy stocks": "To buy stocks, open a Demat account with a broker, search the stock, and place a buy order.",
  "what is intraday trading": "Intraday trading means buying and selling stocks within the same day.",
  "what is nifty": "NIFTY is the National Stock Exchange index that tracks the top 50 companies in India.",
  "what is sensex": "SENSEX is the BSE index tracking the performance of 30 major companies.",
  "tcs stock": "TCS is currently performing well with stable long-term growth and decent dividends.",
  "reliance stock": "Reliance has diversified interests and is considered a blue-chip stock in India.",
  "should i buy infy": "INFY is a solid IT stock, but always check fundamentals and market trends before buying.",
  "what is mutual fund": "A mutual fund pools money from investors to invest in diversified assets.",
  "how to open trading account": "You can open a trading account online through any SEBI-registered broker.",
  "what is IPO": "An IPO or Initial Public Offering is when a company offers shares to the public for the first time.",
  "what is stop loss": "Stop-loss is an order placed to sell a stock when it reaches a certain price to prevent losses.",
  "what is margin trading": "Margin trading allows you to borrow money to buy stocks, increasing both gains and losses.",
  "what is options trading": "Options trading allows buying/selling contracts that give the right to buy or sell a stock.",
  "what is futures trading": "Futures contracts are agreements to buy/sell assets at a future date at a predetermined price.",
  "what is technical analysis": "Technical analysis uses price charts and indicators to predict stock movements.",
  "what is fundamental analysis": "Fundamental analysis evaluates a company's financials to determine its value.",
  "who regulates stock market": "SEBI (Securities and Exchange Board of India) regulates the Indian stock market.",
  "what is dividend": "Dividend is the portion of profit distributed to shareholders.",
  "what is P/E ratio": "P/E ratio compares a company’s share price to its earnings per share.",
  "which is better – mutual funds or stocks": "Mutual funds are safer, while direct stocks can offer higher returns but carry more risk.",
  "what is stock market volatility": "Volatility refers to how much and how quickly the stock price changes.",
  "can i invest with ₹500": "Yes, many mutual funds and stocks allow investments starting as low as ₹100 or ₹500.",
  "what is blue-chip stock": "Blue-chip stocks are established, financially sound companies with strong reputations.",
  "what is SIP": "Systematic Investment Plan (SIP) allows you to invest a fixed amount regularly in mutual funds.",
  "should i invest in gold or stocks": "Gold is a stable asset, while stocks may provide higher returns over long-term.",
  "is zerodha a good broker": "Yes, Zerodha is a top discount broker in India known for its low-cost trading.",
  "best stocks to invest in 2025": "It depends on market trends. Look for fundamentally strong companies with growth potential.",
  "should i sell my shares during market crash": "It's often advised not to panic-sell. Reevaluate based on your long-term goals.",
  "what is share buyback": "A share buyback is when a company repurchases its own shares from the market.",
  "can i lose money in stock market": "Yes, there is a risk of loss. Invest only after proper research.",
  "how to start intraday trading": "You need a trading account and knowledge of market trends, charts, and quick decisions.",
  "what is bull market": "A bull market is when prices are rising or expected to rise.",
  "what is bear market": "A bear market is when prices are falling or expected to fall.",
  "what is portfolio diversification": "Diversification means spreading investments across assets to reduce risk.",
  "what is NAV in mutual funds": "NAV (Net Asset Value) is the price of one unit of a mutual fund.",
  "is it safe to invest in penny stocks": "Penny stocks are risky and often volatile. Invest cautiously.",
  "what is market cap": "Market cap is the total value of a company’s shares = share price × total shares.",
  "how are stock prices determined": "Stock prices are determined by demand and supply in the market.",
  "can i trade without broker": "No, you need a broker to access the stock exchange.",
  "is investing better than saving": "Investing can grow your wealth over time, while saving keeps money safe with low returns.",
  "how to analyse stocks": "You can use technical and fundamental analysis to evaluate stocks.",
  "what is intraday margin": "Intraday margin is the leverage a broker provides for same-day trades.",
  "what is stock split": "A stock split increases the number of shares but reduces the share price proportionally.",
  "what is bonus share": "Bonus shares are additional shares given to existing shareholders for free.",
  "what is rights issue": "A rights issue allows existing shareholders to buy more shares at a discount.",
  "which is better: long term or short term investing": "Long-term investing is generally safer and more rewarding due to compounding.",
  "can i invest in US stocks": "Yes, many brokers now allow investing in US markets from India.",
  "what is FII and DII": "FII = Foreign Institutional Investor, DII = Domestic Institutional Investor.",
  "is trading gambling": "No, trading is based on analysis and strategy, but emotional trading can lead to gambling behavior.",
    "what is arbitrage": "Arbitrage is the simultaneous buying and selling of assets to profit from price differences.",
  "what is brokerage": "Brokerage is the fee charged by a broker for executing trades.",
  "what is leverage in trading": "Leverage allows traders to control a large position with a small amount of capital.",
  "what is liquidity": "Liquidity refers to how easily an asset can be bought or sold without affecting its price.",
  "what is bid and ask price": "Bid is the price buyers are willing to pay, and ask is the price sellers are asking.",
  "what is candle stick chart": "A candlestick chart shows price movements using open, high, low, and close prices.",
  "what is RSI": "RSI or Relative Strength Index is a momentum indicator used in technical analysis.",
  "what is MACD": "MACD stands for Moving Average Convergence Divergence, used to identify trend changes.",
  "what is support and resistance": "Support is a price level where demand is strong, resistance is where supply is strong.",
  "what is breakout in trading": "Breakout is when the price moves beyond a defined support or resistance level.",
  "what is stock term 1": "Stock term 1 refers to a concept in trading or investing, useful for analysis.",
  "what is stock term 2": "Stock term 2 refers to a concept in trading or investing, useful for analysis.",
  "what is stock term 3": "Stock term 3 refers to a concept in trading or investing, useful for analysis.",
  "what is stock term 4": "Stock term 4 refers to a concept in trading or investing, useful for analysis.",
"what is stock term 190": "Stock term 190 refers to a concept in trading or investing, useful for analysis."
  };

  const getResponse = (userInput) => {
    const normalized = userInput.toLowerCase().trim();
    const matched = Object.keys(dummyResponses).find((key) =>
      normalized.includes(key)
    );

    return matched
      ? dummyResponses[matched]
      : "I'm still learning. Try asking: 'What is a bull market?'";
  };

  const handleSend = () => {
    if (!query.trim()) return;

    const userMsg = { sender: 'user', text: query };
    setMessages((prev) => [...prev, userMsg]);
    setQuery('');
    setIsTyping(true);

    setTimeout(() => {
      const botReply = getResponse(query);
      const botMsg = { sender: 'bot', text: botReply };
      setMessages((prev) => [...prev, botMsg]);
      setIsTyping(false);
    }, 1000);
  };

  return (
    <>
      <Menu />
      {/* <Link to="/dashboard" style={{ display: 'block', marginBottom: '0px' }}>Back to Dashboard</Link> */}

 <Link to="/dashboard" className="back-btn">⬅ Back to Dashboard</Link>

      <div style={{ maxWidth: '1000px', margin: '0 auto', marginTop:'0px', padding: '10px', fontFamily: 'sans-serif' }}>
        <h2 style={{ textAlign: 'center' }}>💬 Nova Assistant</h2>
        <div style={{ border: '1px solid #ccc', borderRadius: '10px', height: '400px', padding: '10px', overflowY: 'auto', background: '#f9f9f9' }}>
          {messages.map((msg, index) => (
            <div key={index} style={{ margin: '10px 0', textAlign: msg.sender === 'user' ? 'right' : 'left' }}>
              <div style={{ display: 'inline-block', padding: '10px', borderRadius: '10px', backgroundColor: msg.sender === 'user' ? '#d1e7dd' : '#e2e3e5' }}>
                <strong>{msg.sender === 'user' ? 'You' : 'Nova'}:</strong> {msg.text}
              </div>
            </div>
          ))}
          {isTyping && <p><i>Nova is typing...</i></p>}
          <div ref={messagesEndRef} />
        </div>
        <div style={{ marginTop: '10px', display: 'flex' }}>
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Ask something..."
            style={{ flex: 1, padding: '10px', borderRadius: '4px', border: '1px solid #ccc' }}
          />
          <button
            onClick={handleSend}
            disabled={!query.trim()}
            style={{ padding: '10px', marginLeft: '5px', borderRadius: '4px', background: '#007bff', color: 'white', border: 'none' }}
          >
            Send
          </button>
        </div>
      </div>
    </>
  );
};

export default StockBot;
